# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import gather_pb2 as python__gather_dot_gather__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in python_gather/gather_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EndServer = channel.unary_unary(
                '/gatherproto.GatherService/EndServer',
                request_serializer=python__gather_dot_gather__pb2.EndServerRequest.SerializeToString,
                response_deserializer=python__gather_dot_gather__pb2.EndServerResponse.FromString,
                _registered_method=True)
        self.SendMachineInfo = channel.unary_unary(
                '/gatherproto.GatherService/SendMachineInfo',
                request_serializer=python__gather_dot_gather__pb2.MachineInfoRequest.SerializeToString,
                response_deserializer=python__gather_dot_gather__pb2.MachineInfoResponse.FromString,
                _registered_method=True)
        self.SendStateInfo = channel.unary_unary(
                '/gatherproto.GatherService/SendStateInfo',
                request_serializer=python__gather_dot_gather__pb2.StateInfoRequest.SerializeToString,
                response_deserializer=python__gather_dot_gather__pb2.StateInfoResponse.FromString,
                _registered_method=True)


class GatherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EndServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMachineInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendStateInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EndServer': grpc.unary_unary_rpc_method_handler(
                    servicer.EndServer,
                    request_deserializer=python__gather_dot_gather__pb2.EndServerRequest.FromString,
                    response_serializer=python__gather_dot_gather__pb2.EndServerResponse.SerializeToString,
            ),
            'SendMachineInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMachineInfo,
                    request_deserializer=python__gather_dot_gather__pb2.MachineInfoRequest.FromString,
                    response_serializer=python__gather_dot_gather__pb2.MachineInfoResponse.SerializeToString,
            ),
            'SendStateInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SendStateInfo,
                    request_deserializer=python__gather_dot_gather__pb2.StateInfoRequest.FromString,
                    response_serializer=python__gather_dot_gather__pb2.StateInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gatherproto.GatherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gatherproto.GatherService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EndServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatherproto.GatherService/EndServer',
            python__gather_dot_gather__pb2.EndServerRequest.SerializeToString,
            python__gather_dot_gather__pb2.EndServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMachineInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatherproto.GatherService/SendMachineInfo',
            python__gather_dot_gather__pb2.MachineInfoRequest.SerializeToString,
            python__gather_dot_gather__pb2.MachineInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendStateInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gatherproto.GatherService/SendStateInfo',
            python__gather_dot_gather__pb2.StateInfoRequest.SerializeToString,
            python__gather_dot_gather__pb2.StateInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
