// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: gather.proto

package gather

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EndServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndServerRequest) Reset() {
	*x = EndServerRequest{}
	mi := &file_gather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndServerRequest) ProtoMessage() {}

func (x *EndServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndServerRequest.ProtoReflect.Descriptor instead.
func (*EndServerRequest) Descriptor() ([]byte, []int) {
	return file_gather_proto_rawDescGZIP(), []int{0}
}

type EndServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *EndServerResponse) Reset() {
	*x = EndServerResponse{}
	mi := &file_gather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndServerResponse) ProtoMessage() {}

func (x *EndServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndServerResponse.ProtoReflect.Descriptor instead.
func (*EndServerResponse) Descriptor() ([]byte, []int) {
	return file_gather_proto_rawDescGZIP(), []int{1}
}

func (x *EndServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MachineInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port   string `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	Ip     string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Window string `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
}

func (x *MachineInfoRequest) Reset() {
	*x = MachineInfoRequest{}
	mi := &file_gather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfoRequest) ProtoMessage() {}

func (x *MachineInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfoRequest.ProtoReflect.Descriptor instead.
func (*MachineInfoRequest) Descriptor() ([]byte, []int) {
	return file_gather_proto_rawDescGZIP(), []int{2}
}

func (x *MachineInfoRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *MachineInfoRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MachineInfoRequest) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

type MachineInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *MachineInfoResponse) Reset() {
	*x = MachineInfoResponse{}
	mi := &file_gather_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfoResponse) ProtoMessage() {}

func (x *MachineInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gather_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfoResponse.ProtoReflect.Descriptor instead.
func (*MachineInfoResponse) Descriptor() ([]byte, []int) {
	return file_gather_proto_rawDescGZIP(), []int{3}
}

func (x *MachineInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StateInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Leader        bool   `protobuf:"varint,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Allowtransfer bool   `protobuf:"varint,2,opt,name=allowtransfer,proto3" json:"allowtransfer,omitempty"`
	Addrstring    string `protobuf:"bytes,3,opt,name=addrstring,proto3" json:"addrstring,omitempty"`
}

func (x *StateInfoRequest) Reset() {
	*x = StateInfoRequest{}
	mi := &file_gather_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateInfoRequest) ProtoMessage() {}

func (x *StateInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gather_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateInfoRequest.ProtoReflect.Descriptor instead.
func (*StateInfoRequest) Descriptor() ([]byte, []int) {
	return file_gather_proto_rawDescGZIP(), []int{4}
}

func (x *StateInfoRequest) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *StateInfoRequest) GetAllowtransfer() bool {
	if x != nil {
		return x.Allowtransfer
	}
	return false
}

func (x *StateInfoRequest) GetAddrstring() string {
	if x != nil {
		return x.Addrstring
	}
	return ""
}

type StateInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StateInfoResponse) Reset() {
	*x = StateInfoResponse{}
	mi := &file_gather_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateInfoResponse) ProtoMessage() {}

func (x *StateInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gather_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateInfoResponse.ProtoReflect.Descriptor instead.
func (*StateInfoResponse) Descriptor() ([]byte, []int) {
	return file_gather_proto_rawDescGZIP(), []int{5}
}

func (x *StateInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_gather_proto protoreflect.FileDescriptor

var file_gather_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x12, 0x0a, 0x10, 0x45,
	0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x2d, 0x0a, 0x11, 0x45, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x50,
	0x0a, 0x12, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77,
	0x22, 0x2f, 0x0a, 0x13, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x70, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x24, 0x0a,
	0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x72, 0x73, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x72, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x22, 0x2d, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x32, 0x87, 0x02, 0x0a, 0x0d, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x09, 0x45, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x1d, 0x2e, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x45, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x56, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x2e, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0d, 0x53, 0x65,
	0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x2e, 0x67, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2f, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gather_proto_rawDescOnce sync.Once
	file_gather_proto_rawDescData = file_gather_proto_rawDesc
)

func file_gather_proto_rawDescGZIP() []byte {
	file_gather_proto_rawDescOnce.Do(func() {
		file_gather_proto_rawDescData = protoimpl.X.CompressGZIP(file_gather_proto_rawDescData)
	})
	return file_gather_proto_rawDescData
}

var file_gather_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gather_proto_goTypes = []any{
	(*EndServerRequest)(nil),    // 0: gatherproto.EndServerRequest
	(*EndServerResponse)(nil),   // 1: gatherproto.EndServerResponse
	(*MachineInfoRequest)(nil),  // 2: gatherproto.MachineInfoRequest
	(*MachineInfoResponse)(nil), // 3: gatherproto.MachineInfoResponse
	(*StateInfoRequest)(nil),    // 4: gatherproto.StateInfoRequest
	(*StateInfoResponse)(nil),   // 5: gatherproto.StateInfoResponse
}
var file_gather_proto_depIdxs = []int32{
	0, // 0: gatherproto.GatherService.EndServer:input_type -> gatherproto.EndServerRequest
	2, // 1: gatherproto.GatherService.SendMachineInfo:input_type -> gatherproto.MachineInfoRequest
	4, // 2: gatherproto.GatherService.SendStateInfo:input_type -> gatherproto.StateInfoRequest
	1, // 3: gatherproto.GatherService.EndServer:output_type -> gatherproto.EndServerResponse
	3, // 4: gatherproto.GatherService.SendMachineInfo:output_type -> gatherproto.MachineInfoResponse
	5, // 5: gatherproto.GatherService.SendStateInfo:output_type -> gatherproto.StateInfoResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gather_proto_init() }
func file_gather_proto_init() {
	if File_gather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gather_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gather_proto_goTypes,
		DependencyIndexes: file_gather_proto_depIdxs,
		MessageInfos:      file_gather_proto_msgTypes,
	}.Build()
	File_gather_proto = out.File
	file_gather_proto_rawDesc = nil
	file_gather_proto_goTypes = nil
	file_gather_proto_depIdxs = nil
}
